name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag simplewebapp:$(date +%s)
    - name: Tag the Docker image
      run: docker tag simplewebapp:$(date +%s) tsainit/simplewebapp:$(date +%s)
    - name: Login to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Push the Docker image
      run: docker push tsainit/simplewebapp:$(date +%s)
